language: generic
addons:
  apt:
    packages:
      - tcl

install:
  # Install tcllib
  - wget https://core.tcl.tk/tcllib/uv/tcllib-1.19.zip
  - unzip tcllib-1.19.zip
  - cd tcllib-1.19
  - sudo tclsh installer.tcl -no-gui -no-wait
  - cd ..
  # Install install_module
  - git clone https://github.com/lawrencewoodman/installmodule_tcl
  # Install Tcl ornament module
  - git clone https://github.com/lawrencewoodman/ornament_tcl
  - sudo tclsh installmodule_tcl/installmodule.tcl ornament_tcl/ornament-*.tm

script:
  # Run the tests
  - tclsh tests/all.tcl
