language: generic
addons:
  apt:
    packages:
      - tcl
script:
  # Install tcllib
  - wget https://core.tcl.tk/tcllib/uv/tcllib-1.19.zip
  - unzip tcllib-1.19.zip
  - cd tcllib-1.19
  - sudo tclsh installer.tcl -dry-run -no-gui -no-wait

  - tclsh info.tcl
  # Run the tests
  - tclsh tests/*.test.tcl
