language: generic
addons:
  apt:
    packages:
      - tcl

install:
  # Install tcllib
  - wget https://core.tcl.tk/tcllib/uv/tcllib-1.19.zip
  - unzip tcllib-1.19.zip
  - cd tcllib-1.19
  - sudo tclsh installer.tcl -no-gui -no-wait
  - cd ..

script:
  # Run the tests
  - tclsh tests/*.test.tcl
