#!/usr/bin/env tclsh
# Fake cmark for testing as it isn't easy to install cmark
# on travis-ci.


set mdArgs [list]
foreach arg $argv {
  if {$arg ne "--unsafe"} {lappend mdArgs $arg}
  if {$arg eq "-nnnnnn"} {
    puts stderr "Usage: cmark"
    exit 1
  }
}

if {[llength $mdArgs] == 1} {
  lassign $mdArgs filename
  if {[string match "*simple.md" $filename]} {
    puts {<h1>This is a title</h1>
<p>This is a new paragraph.</p>}
  }
} else {
  set src [read stdin]
  puts {<h1>This is a title</h1>
<p>This is a new paragraph.</p>}
}
